apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: three-tier-app
  labels:
    app: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: duybo95/rds-app-api:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PWD
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_DATABASE
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5 
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier-app
  labels:
    app: backend-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: backend-app 
